background_opacity 0.7

enabled_layouts grid

# Move the active window in the indicated direction
map ctrl+shift+h move_window left
map ctrl+shift+j move_window down
map ctrl+shift+l move_window right
map ctrl+shift+k move_window up

# Switch focus to the neighboring window in the indicated direction
map ctrl+alt+h neighboring_window left
map ctrl+alt+j neighboring_window down
map ctrl+alt+k neighboring_window up
map ctrl+alt+l neighboring_window right

